export const BOARD_CONSTANTS = {
  CREATE_BOARD: "CREATE_BOARD",
  DELETE_BOARD: "DELETE_BOARD",
  ADD_BOARD: "ADD_BOARD",
  SELECT_BOARD: "SELECT_BOARD",
  REMOVE_BOARD: "REMOVE_BOARD",
  CREATE_TASK: "CREATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  UPDATE_TASK_STATUS: "UPDATE_TASK_STATUS",
};
